- name: copy prometheus configuration
  ansible.builtin.template:
    src: prometheus.yml
    dest: /opt/prometheus/prometheus.yml
  notify: Restart prometheus

- name: copy alerts configuration
  ansible.builtin.template:
    src: alert_rules.yml
    dest: /opt/prometheus/alert_rules.yml
  notify: Restart prometheus

- name: start prometheus
  ansible.builtin.systemd:
    name: prometheus
    state: started
    enabled: yes

- name: Wait for prometheus to start
  ansible.builtin.wait_for:
    port: 9090
    delay: 10 #wait for 30sec
    timeout: 30 #stop waiting after 30sec that is a failure