- name: Set up hostname
  ansible.builtin.shell: set-hostname {{COMPONENT}}

- name: Install prometheus node exporter
  ansible.builtin.include_role:
    name: prometheus
    tasks_from: client

- name: Install Ansible AWS SSM Python3 Dependencies
  ansible.builtin.pip:
    name: "{{item}}"
    executable: pip3
  loop:
    - botocore
    - boto3
