- name: Install Ansible AWS SSM Python3 Dependencies
  ansible.builtin.pip:
    name: "{{item}}"
    executable: pip3
  loop:
    - botocore
    - boto3
    
- name: copy {{COMPONENT}} systemd file
  ansible.builtin.template:
    src: systemd.service
    dest: /etc/systemd/system/{{COMPONENT}}.service

- name: restart {{COMPONENT}}
  ansible.builtin.systemd:
    name: "{{COMPONENT}}"
    state: restarted
    enabled: yes
    daemon-reload: yes

- name: Include filebeat installation
  ansible.builtin.include_role:
    name: elk
    tasks_from: filebeat

