groups:
  - name: Alerts
    rules:
      - alert: InstanceDown
        expr: up == 0
        for: 1m
        labels:
          severity: critical
        annotations: {% raw %}
          summary: "Instance Down - [{{ $labels.instance}}]" 
          description: "Instance Down - [{{ $labels.instance}}]" {% endraw %}
          #ignoring above 2 lines in ansible way
{% for component in COMPONENTS %}
      - alert: service down {{component}}
        expr: node_systemd_unit_state{name="{{component}}.service",state="active"} < 1
        for: 1m
        labels:
          severity: critical
        annotations: {% raw %}
          summary: "Instance Down - [{{ $labels.instance}}]" 
          description: "Instance Down - [{{ $labels.instance}}]" {% endraw %}
          #ignoring above 2 lines in ansible way
          
{% endfor %}
