groups:
  - name: Alerts
    rules:
      - alert: InstanceDown
        expr: up == 0
        for: 1m
        labels:
          severity: critical
        annotations:
        #ignoring below 2 lines in ansible way
          {% summary: "Instance Down - [{{ $labels.instance}}]" -%}
          {% description: "Instance Down - [{{ $labels.instance}}]" -%}