global:
  scrape_interval: 15s
  evaluation_interval: 15s



alerting:
  alertmanagers:
    - static_configs:
        - targets:



rule_files:

scrape_configs:

  - job_name: "prometheus"
    static_configs:
    #this is the target u should talk to
      - targets: 
          - "172.31.84.216:9100"